import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Sidebar from "../components/sidebar/Sidebar";
import SpotifyTopArtists from "../components/spotify/SpotifyTopArtists";
import SpotifySavedTracks from "../components/spotify/SpotifySavedTracks";
import Section from "../components/Section";
import School from "../components/School";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const [isOpen, setIsOpen] = useState(false);

  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setIsOpen(!isOpen);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Sidebar /> */}
      <main>
        <div className="banner">
          <h1 className="hover-color">HI I'M</h1>

          <Section />
          <h2 className="hover-color">DATA ANALYST</h2>
          <h2 className="hover-color">WEB DEVELOPER</h2>
          <h3 className="hover-color">EXPERIENCE</h3>
          <h3 className="hover-color">EDUCATION</h3>
          {/* <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div> */}
          {/* <SpotifySavedTracks />

          <SpotifyTopArtists /> */}
        </div>
        <Section date="2016" dateLeft={true}>
          <School />
        </Section>
        <Section date="2017" dateLeft={false}>
          <School />
        </Section>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
