import React from "react";
import { type NextPage } from "next";
import Head from "next/head";

//type Props = {}

const todolist: NextPage = (props: Props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen flex-col justify-center justify-items-center">
        <div className="container flex w-full flex-col justify-center justify-items-center">
          <span className="m-4 flex h-16 w-full flex-col justify-center justify-items-center rounded-2xl border border-green-500">
            <h1 className="text-black-900">Hi</h1>
          </span>
        </div>
      </main>
    </>
  );
};

export default todolist;
